## Scalers, Vectors, Matrices and Tensors
Here's a comprehensive guide to using scalars, vectors, matrices, and tensors in Python, primarily using the NumPy library.

In [41]:
import sys
import numpy as np
print(f'Python Version:: {sys.version}')
print(f'Numpy Version:: {np.__version__}')

Python Version:: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Numpy Version:: 2.0.0


#### Scalers - A scalar is a single number.

In [6]:
import numpy as np
scaler = np.array(5) # Defines scaler
print(f'Scaler:: {scaler}')

Scaler:: 5


#### Vectors - A Vector is a single dimensional array

In [43]:
vector = np.array([1,2,3,4,5]) # Define a vector
print(f'vector:: {vector}')
print(f'vector dimensions:: {vector.shape}')
print(f'vector size:: {vector.size}')

vector:: [1 2 3 4 5]
vector dimensions:: (5,)
vector size:: 5


#### Matrices - A Matrix is a 2 dimensional array

In [51]:
matrix = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(f'matrix::\n{matrix}')
print('--------------------------------')
print(f'matrix shape:: {matrix.shape}')
print(f'matrix size:: {matrix.size}')
print('--------------------------------')
another_matrix = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(f'another matrix::\n{another_matrix}')


matrix::
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
--------------------------------
matrix shape:: (2, 5)
matrix size:: 10
--------------------------------
another matrix::
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [61]:
# define a matrix of a given dimension
matrix_a = np.ones((4,3))
print(f'np.ones((4,3)::\n{matrix_a}')
print(f'matrix shape:: {matrix_a.shape}')
print(f'matrix size:: {matrix_a.size}')
print('--------------------------------')
matrix_b = np.zeros((3,3))
print(f'np.zeros((3,3)::\n{matrix_b}')
print(f'matrix shape:: {matrix_b.shape}')
print(f'matrix size:: {matrix_b.size}')
print('--------------------------------')
matrix_c = np.zeros((5,5))
print(f'np.zeros((5,5)::\n{matrix_c}')
print(f'matrix shape:: {matrix_c.shape}')
print(f'matrix size:: {matrix_c.size}')

np.ones((4,3)::
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
matrix shape:: (4, 3)
matrix size:: 12
--------------------------------
np.zeros((3,3)::
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
matrix shape:: (3, 3)
matrix size:: 9
--------------------------------
np.zeros((5,5)::
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
matrix shape:: (5, 5)
matrix size:: 25


#### Tensors - A tensor is a multi-dimensional array. Tensors generalize scalars, vectors, and matrices to higher dimensions.

In [9]:
tensor = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
print(f'tensor:: {tensor}')

tensor:: [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


## Operations

In [12]:
## Scaler Operations

a = 1
b = 2

print(f'a:: {b}, b:: {b}')
print('--------------------------------')
print('Scaler Addition, (a+b):: ', a+b)
print('Scaler Subtraction, (a-b):: ', a-b)
print('Scaler MUltiplication, (a*b):: ', a*b)
print('Scaler Division::, (a/b) ', a/b)

a:: 2, b:: 2
--------------------------------
Scaler Addition, (a+b)::  3
Scaler Subtraction, (a-b)::  -1
Scaler MUltiplication, (a*b)::  2
Scaler Division::, (a/b)  0.5


In [16]:
# Vector Operations
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(f'a:: {a}, b:: {b}')
print('-------------------------------------------------')
print('Vector Addition,         (a+b):: ', a+b)
print('Vector Subtraction,      (a-b):: ', a-b)
print('Vector MUltiplication,   (a*b):: ', a*b)
print('Vector Division,         (a/b):: ', a/b)

a:: [1 2 3 4 5], b:: [ 6  7  8  9 10]
-------------------------------------------------
Vecotr Addition,         (a+b)::  [ 7  9 11 13 15]
Vecotr Subtraction,      (a-b)::  [-5 -5 -5 -5 -5]
Vecotr MUltiplication,   (a*b)::  [ 6 14 24 36 50]
Vecotr Division,         (a/b)::  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [29]:
# Matrix Operations
a = np.array([[1,2]])
b = np.array([[6,7],[8,9],[10,11]])

print(f'a:: {a},\nb:: {b}')
print('-------------------------------------------------')
print('Matrix Addition\, (a+b)::\n', a+b)
print('Matrix Subtraction\, (a-b)::\n', a-b)

a:: [[1 2]],
b:: [[ 6  7]
 [ 8  9]
 [10 11]]
-------------------------------------------------
Matrix Addition\, (a+b)::
 [[ 7  9]
 [ 9 11]
 [11 13]]
Matrix Subtraction\, (a-b)::
 [[-5 -5]
 [-7 -7]
 [-9 -9]]


<>:7: SyntaxWarning: invalid escape sequence '\,'
<>:8: SyntaxWarning: invalid escape sequence '\,'
<>:7: SyntaxWarning: invalid escape sequence '\,'
<>:8: SyntaxWarning: invalid escape sequence '\,'
C:\Users\Sean\AppData\Local\Temp\ipykernel_11328\2978799259.py:7: SyntaxWarning: invalid escape sequence '\,'
  print('Matrix Addition\, (a+b)::\n', a+b)
C:\Users\Sean\AppData\Local\Temp\ipykernel_11328\2978799259.py:8: SyntaxWarning: invalid escape sequence '\,'
  print('Matrix Subtraction\, (a-b)::\n', a-b)


In [39]:
import numpy as np

# Define the matrices
a = np.array([[1, 2, 3]])
b = np.array([[6, 7], [8, 9], [10, 11]])

print(f'a:: {a}\nb:: {b}')
print('-------------------------------------------------')
print('Matrix Multiplication, (a*b):: ', np.dot(a, b))

# To perform the matrix division a/b, we need to ensure that the dimensions align correctly.
# Since a is a 1×3 matrix and the pseudo-inverse of b will be a 2×3 matrix,
# we should transpose the result of the pseudo-inverse to get a 3×2 matrix,
# which can then be multiplied by a.

# To perform matrix division a/b:
# - Compute the pseudo-inverse of b.
# - Transpose the pseudo-inverse to match dimensions.
# - Multiply a by the transposed pseudo-inverse.

# Compute the pseudo-inverse of b
b_pseudo_inverse = np.linalg.pinv(b)

# Perform the matrix multiplication a * b_pseudo_inverse.T
print('Matrix Division, (a/b):: ', np.dot(a, b_pseudo_inverse.T))


a:: [[1 2 3]]
b:: [[ 6  7]
 [ 8  9]
 [10 11]]
-------------------------------------------------
Matrix Multiplication, (a*b)::  [[52 58]]
Matrix Division, (a/b)::  [[ 2.5 -2. ]]


In [40]:
# Tensor Operations
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# Tensor addition
tensor_sum = a + b

# Tensor element-wise multiplication
tensor_elementwise_product = a * b

print("Tensor Sum:")
print(tensor_sum)
print("Tensor Element-wise Product:")
print(tensor_elementwise_product)


Tensor Sum:
[[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]
Tensor Element-wise Product:
[[[  9  20]
  [ 33  48]]

 [[ 65  84]
  [105 128]]]
